---
abstract: 'Perl Binding for AAlib'
author:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Devel::CheckLib: 0
  Module::Build: 0.38
  Module::Build::XSUtil: 0.02
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-AAlib
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - benchmark
    - builder
provides:
  Text::AAlib:
    file: lib/Text/AAlib.pm
    version: 0.05
requires:
  Term::ANSIColor: 0
  XSLoader: 0.02
  perl: 5.008001
resources:
  bugtracker: https://github.com/syohex/p5-Text-AAlib/issues
  homepage: https://github.com/syohex/p5-Text-AAlib
  repository: git://github.com/syohex/p5-Text-AAlib.git
version: 0.05
